apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  creationTimestamp: null
  labels:
    created-by: kubeless
    function: function-services
  name: function-services
  namespace: functions
spec:
  checksum: sha256:31dc572e923411e839920c66a6220b5b7677f80fd5bbe35ccc71be9e0e801764
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      selector: null
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - imagePullPolicy: Always
              name: ""
              resources: {}
    status: {}
  deps: |-
    python-dateutil
    pandas
    numpy
  function: https://s3.amazonaws.com/will-kops-state-store-2/services/function-0.0.24.zip?raw=true
  function-content-type: url+zip
  handler: handler.execute
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: python3.7
  service:
    clusterIP: None
    ports:
      - name: http-function-port
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      created-by: kubeless
      function: function-services
    type: ClusterIP
  timeout: "180"
