apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  creationTimestamp: null
  labels:
    created-by: kubeless
    function: function-services
  name: function-services
  namespace: functions
spec:
  checksum: sha256:92ae8ea2592218c6f75515601ea8adb89a20188423c37f97acf3907a18b0c6da
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      selector: null
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - imagePullPolicy: Always
              name: ""
              resources: {}
    status: {}
  deps: |-
    python-dateutil
    pandas
    numpy
  function: https://s3.amazonaws.com/will-kops-state-store-2/services/function-0.0.27.zip?raw=true
  function-content-type: url+zip
  handler: handler.execute
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: python3.7
  service:
    clusterIP: None
    ports:
      - name: http-function-port
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      created-by: kubeless
      function: function-services
    type: ClusterIP
  timeout: "180"
